apiVersion: v1
kind: Service
metadata:
  labels:
    app: tushar-app
  name: tushar-service
  namespace: default
spec: 
  type: NodePort  
  ports:
    - name: http
      protocol: TCP
      port: 3000    
  selector:
    app: tushar-app