apiVersion: v1
kind: Service
metadata:
  labels:
    app: tushar-deployment-prjkt
  name: tushar-deployment-prjkt
  namespace: default
spec:
  type: NodePort  
  ports:
    - name: http
      protocol: TCP
      port: 3000    
  selector:
    app: tushar-deployment-prjkt