apiVersion: v1
kind: Service
metadata:
  name: tushar-service-prac10
  namespace: default
  labels:
    app: tushar-prac10
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 3000         # Port exposed by the service
      targetPort: 3000   # Port on the container
  selector:
    app: tushar-prac10   # Match labels in the Deployment
